AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  App:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: serverless-qiita-team-template
      Runtime: go1.x 
      CodeUri: build
      Timeout: 1
