AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Parameters:
  QiitaAccessToken:
    Type: String
  QiitaTeamName:
    Type: String
  QiitaTeamTemplateId:
    Type: String
  KmsKeyId:
    Type: String
  ScheduleExpression:
    Type: String

Resources:
  App:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: serverless-qiita-team-template
      Runtime: go1.x 
      CodeUri: build
      Timeout: 60
      KmsKeyArn:
        Fn::Join:
          - ""
          - - "arn:aws:kms:"
            - !Ref "AWS::Region"
            - ":"
            - !Ref "AWS::AccountId"
            - ":key/"
            - !Ref KmsKeyId
      Policies:
        - AWSLambdaExecute
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - kms:Decrypt
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:kms:"
                    - !Ref "AWS::Region"
                    - ":"
                    - !Ref "AWS::AccountId"
                    - ":key/"
                    - !Ref KmsKeyId
      Environment:
        Variables:
          QIITA_ACCESS_TOKEN: !Ref QiitaAccessToken
          QIITA_TEAM_NAME: !Ref QiitaTeamName
          QIITA_TEAM_TEMPLATE_ID: !Ref QiitaTeamTemplateId
      Events:
        Schedule:
          Type: Schedule
          Properties:
            Schedule: !Ref ScheduleExpression
